//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public Contacts()
        {
            this.Contribution = new HashSet<Contribution>();
            this.Goods = new HashSet<Goods>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<Contribution> Contribution { get; set; }
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
